### ISSUE TITLE
[CUS] - we should have separate branch for each version or should have only latest one.

### ISSUE THREAD

**Issue by rutvikpadhiyar000** [PythonMathCalculator/python-math-calculator#13]
**What is the issue**

If we add all versions in repository togather older versions that a person dont need will be present in their clone too

**How can it be fixed**

We can have separate branch for separate versions or just remove the old ones

**Additional Context**

Enter Here.

**Linking Pull Request or Issues**

Enter Here.

**Comment by CodeAsherPlayz** [comment]
Can you help me research on something. I heard that you can add folders in GitHub but I do not know how. I see other repositories have directories so we can make a directory and move all the code there.

**Comment by rutvikpadhiyar000** [comment]
Just create newfile and give directory name befor that
Ex.
new-directory/new-file

**Comment by rutvikpadhiyar000** [comment]
Or you can do it locally and push the changes to github

**Comment by CodeAsherPlayz** [comment]
I moved it already. So a new folder is okay?
