### ISSUE TITLE
[FTU] - Add Pi

### ISSUE THREAD

**Issue by CodeAsherPlayz** [PythonMathCalculator/python-math-calculator#20]
**Is your feature request related to a problem? Please describe.**

Nil.

**What is the feature request?**

Add Pi.

**Describe the solution you'd like**

Nil.

**Describe alternatives you've considered**

Nil.

**Additional context**

Nil.

**Comment by rutvikpadhiyar000** [comment]
adding pi is easy just use
`from math import pi`

**Comment by rutvikpadhiyar000** [comment]
![image](https://user-images.githubusercontent.com/76583071/103473049-50377680-4dba-11eb-811b-bfe32956db72.png)

**Comment by CodeAsherPlayz** [comment]
yeah, but we want to give different variations of pi.

**Comment by CodeAsherPlayz** [comment]
22 over 7, 3.14 and calculator pi

**Comment by rutvikpadhiyar000** [comment]
That seems good too
