### ISSUE TITLE
[FTU] - Add front end to the app.

### ISSUE THREAD

**Issue by rutvikpadhiyar000** [PythonMathCalculator/python-math-calculator#9]
**Is your feature request related to a problem? Please describe.**

**What is the feature request?**
It will makebusers job much easier if the app has frontend which can make use of app much more pleasant and userfriendly.

Enter Here.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

In future we may add more features and maybe able to deploy it on the web.

**Comment by CodeAsherPlayz** [comment]
I see. However as you know I'm not so much of a expert Coder so I may have you handle it. If there is a necessity for HTML or CSS, you can look at my repository on HTML.

**Comment by CodeAsherPlayz** [comment]
I decided to add it to my HTML login page! If you want, you may go to my account and see the repository. We should discuss this more in the Conversations tab.

**Comment by CodeAsherPlayz** [comment]
I actually don't mind this idea but I didn't have the feeling to take it that far. We can still continue with this but we might need more manpower.

**Comment by rutvikpadhiyar000** [comment]
I think we should leave it for now.
What do you think?

**Comment by CodeAsherPlayz** [comment]
Yeah, we leave it for now.

**Comment by CodeAsherPlayz** [comment]
Maybe when more people find this repository then will work on this. By the way, we country do you live in?

**Comment by rutvikpadhiyar000** [comment]
I am from india and you?

**Comment by CodeAsherPlayz** [comment]
Singapore

**Comment by CodeAsherPlayz** [comment]
Your English is quite good :D

**Comment by rutvikpadhiyar000** [comment]
We indians learn it from childhood like i am studying in english from when i was 11

**Comment by rutvikpadhiyar000** [comment]
It's widely spoken in india

**Comment by CodeAsherPlayz** [comment]
Oh... I see

**Comment by rutvikpadhiyar000** [comment]
You have a youtube channel listed in your profile but it shows 404

**Comment by rutvikpadhiyar000** [comment]
And yeah i think this issue should be closed for now

**Comment by CodeAsherPlayz** [comment]
Yeah I have a YouTube channel but I don't what happened to it

> You have a youtube channel listed in your profile but it shows 404

**Comment by CodeAsherPlayz** [comment]
It's kinda dead though haha

**Comment by rutvikpadhiyar000** [comment]
Haha

**Comment by CodeAsherPlayz** [comment]
It's actually dead because I am working on GitHub repositories now. Though I need more people to recognise the repositories.

**Comment by rutvikpadhiyar000** [comment]
Do you contribute to other projects?
Like except yours?
Thats a good way to get noticed.

**Comment by CodeAsherPlayz** [comment]
> Do you contribute to other projects?
> Like except yours?
> Thats a good way to get noticed.

Ahhh I see.. I don't know which repositories to work on though.

**Comment by CodeAsherPlayz** [comment]
By the way which state of India I want to see the time difference.

**Comment by rutvikpadhiyar000** [comment]
Gujarat

**Comment by rutvikpadhiyar000** [comment]
Just

> > Do you contribute to other projects?
> > Like except yours?
> > Thats a good way to get noticed.
> 
> Ahhh I see.. I don't know which repositories to work on though.

Just go to issues at top and search lable:'lable-name'
Language:'language-name'

**Comment by CodeAsherPlayz** [comment]
> Just
> 
> > > Do you contribute to other projects?
> > > Like except yours?
> > > Thats a good way to get noticed.
> > 
> > 
> > Ahhh I see.. I don't know which repositories to work on though.
> 
> Just go to issues at top and search lable:'lable-name'
> Language:'language-name'

Thanks!

**Comment by rutvikpadhiyar000** [comment]
For start you can search 'begginer' or 'good first issue' for lable

**Comment by rutvikpadhiyar000** [comment]
Something like `label:"Good first issue" language:Python`

**Comment by CodeAsherPlayz** [comment]
@rutvikpadhiyar000 please check on #14 thanks!
